# Generated by Django 2.0.5 on 2019-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190216_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='pending',
            fields=[
                ('auto_increment_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('desc', models.TextField(default='')),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('contact_phone', models.IntegerField(default=0)),
                ('address', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
