# Generated by Django 2.0.5 on 2019-02-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190219_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='auto_increment_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='auto_increment_id',
        ),
        migrations.AddField(
            model_name='pending',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
