# Generated by Django 2.0.5 on 2019-02-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190219_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pending',
            old_name='id',
            new_name='id_inc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='id_inc',
        ),
    ]
