# Generated by Django 2.0.5 on 2019-02-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190219_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
